development:
  adapter: postgresql
  encoding: unicode
  database: line_of_life_development
  pool: 10
  password: root
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: line_of_life_test
  pool: 10
  password: root

staging:
  adapter: postgresql
  encoding: unicode
  database: line_of_life_staging
  pool: 10
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: line_of_life_production
  pool: 10
  password: